version: "3"

services:
  app:
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${CONTAINER}.rule=Host(`${TRAEFIK_HOST}`)"
      - "traefik.http.middlewares.${CONTAINER}.compress=true"
      - "traefik.http.routers.${CONTAINER}.middlewares=${CONTAINER}"
      - "traefik.http.services.${CONTAINER}.loadBalancer.server.port=80"

  websockets:
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${CONTAINER}_ws.rule=Host(`${TRAEFIK_HOST}`) && Path(`/ws`)"
      - "traefik.http.routers.${CONTAINER}_ws.middlewares=${CONTAINER}_ws"
      - "traefik.http.middlewares.${CONTAINER}_ws.chain.middlewares=${CONTAINER}_ws-compress,${CONTAINER}_ws-headers"
      - "traefik.http.middlewares.${CONTAINER}_ws-compress.compress=true"
      - "traefik.http.middlewares.${CONTAINER}_ws-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.services.${CONTAINER}_ws.loadBalancer.server.port=6001"

networks:
  traefik:
    external: true
